services:
  - type: web
    name: MessMenuApi
    env: docker
    buildCommand: ""
    startCommand: ""  
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: TZ
        value: "Asia/Kolkata"  # Set timezone to IST
