services:
  - type: web
    name: MessMenuApi
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y wget unzip
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      dpkg -i google-chrome-stable_current_amd64.deb || apt-get -f install -y
      pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
